import { countryLabel } from './countries';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildMarkdown(doc: any): string {
  const b = doc.basics;
  const lines: string[] = [];

  const name = b.name;
  const fullName = [name?.first, name?.middle, name?.last].filter(Boolean).join(' ');
  lines.push(`# ${fullName}`);
  if (b.headline) lines.push(`**${b.headline}**`);

  const contactParts: string[] = [];
  if (b.email) contactParts.push(b.email);
  if (b.phone) contactParts.push(b.phone);
  const loc = [b.location?.city, b.location?.region, b.location?.countryCode]
    .filter(Boolean)
    .join(', ');
  if (loc) contactParts.push(loc);
  if (contactParts.length > 0) lines.push(contactParts.join(' | '));

  if (b.profiles) {
    const profileParts: string[] = [];
    for (const p of b.profiles) {
      if (p.url) profileParts.push(`[${p.network}](${p.url})`);
      else if (p.username) profileParts.push(`${p.network}: ${p.username}`);
    }
    if (profileParts.length > 0) lines.push(profileParts.join(' | '));
  }
  lines.push('');

  if (b.summary) {
    lines.push('## Summary');
    lines.push(b.summary);
    lines.push('');
  }

  if (doc.work?.length > 0) {
    lines.push('## Experience');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const w of doc.work as any[]) {
      lines.push(`### ${w.position}, ${w.company}`);
      const range = [w.startDate, w.current ? 'Present' : w.endDate].filter(Boolean).join(' - ');
      const dateLoc = [range, w.location].filter(Boolean).join(' | ');
      if (dateLoc) lines.push(`*${dateLoc}*`);
      if (w.summary) { lines.push(''); lines.push(w.summary); }
      if (w.highlights?.length > 0) {
        lines.push('');
        for (const h of w.highlights) lines.push(`- ${h}`);
      }
      lines.push('');
    }
  }

  if (doc.education?.length > 0) {
    lines.push('## Education');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const e of doc.education as any[]) {
      lines.push(`### ${e.studyType} in ${e.area}, ${e.institution}`);
      const range = [e.startDate, e.endDate].filter(Boolean).join(' - ');
      const extra = [range, e.score ? `GPA: ${e.score}` : ''].filter(Boolean).join(' | ');
      if (extra) lines.push(`*${extra}*`);
      if (e.courses?.length > 0) { lines.push(''); lines.push(`Courses: ${e.courses.join(', ')}`); }
      lines.push('');
    }
  }

  if (doc.skills?.length > 0) {
    lines.push('## Skills');
    for (const s of doc.skills) {
      lines.push(`**${s.category}** (${s.level}): ${s.keywords.join(', ')}`);
    }
    lines.push('');
  }

  if (doc.languages?.length > 0) {
    lines.push('## Languages');
    for (const l of doc.languages) lines.push(`- ${l.language} (${l.fluency})`);
    lines.push('');
  }

  if (doc.certificates?.length > 0) {
    lines.push('## Certifications');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const c of doc.certificates as any[]) {
      const parts = [c.name];
      if (c.issuer) parts.push(c.issuer);
      if (c.date) parts.push(c.date);
      lines.push(`- ${parts.join(', ')}`);
    }
    lines.push('');
  }

  if (doc.awards?.length > 0) {
    lines.push('## Honours and Awards');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const a of doc.awards as any[]) {
      const parts = [a.title];
      if (a.issuer) parts.push(a.issuer);
      if (a.date) parts.push(a.date);
      lines.push(`- ${parts.join(', ')}`);
      if (a.description) lines.push(`  ${a.description}`);
    }
    lines.push('');
  }

  const wa = doc.compliance?.workAuthorization;
  if (wa && wa.authorized !== undefined) {
    lines.push('## Work Authorization');
    lines.push(`Authorized to work: ${wa.authorized ? 'Yes' : 'No'}`);
    if (wa.countries?.length > 0) {
      lines.push(`Countries: ${wa.countries.map((c: string) => countryLabel(c)).join(', ')}`);
    }
    if (wa.requiresSponsorship !== undefined) {
      lines.push(`Requires sponsorship: ${wa.requiresSponsorship ? 'Yes' : 'No'}`);
    }
    lines.push('');
  }

  lines.push('---');
  const genDate = new Date(doc.$credentia.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  lines.push(`*Generated by Credentia One on ${genDate}*`);
  if (doc.$credentia.verifyUrl) {
    lines.push(`*Verification: ${doc.$credentia.verifyUrl}*`);
  }

  return lines.join('\n');
}
