import type { CredentiaDocument } from './schema';
import { countryLabel } from './countries';

function formatDate(d: { month: string; year: string } | undefined): string {
  if (!d || (!d.month && !d.year)) return '';
  const months = [
    '', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  const m = months[parseInt(d.month, 10)] ?? d.month;
  return m ? `${m} ${d.year}` : d.year;
}

function dateRange(
  start: { month: string; year: string } | undefined,
  end: { month: string; year: string } | undefined,
  current: boolean,
): string {
  const s = formatDate(start);
  const e = current ? 'Present' : formatDate(end);
  if (s && e) return `${s} - ${e}`;
  if (s) return s;
  if (e) return e;
  return '';
}

export function buildMarkdown(doc: CredentiaDocument): string {
  const b = doc.basics;
  const lines: string[] = [];

  // Header
  const fullName = [b.firstName, b.middleName, b.lastName].filter(Boolean).join(' ');
  lines.push(`# ${fullName}`);
  if (b.headline) lines.push(`**${b.headline}**`);

  const contactParts: string[] = [];
  if (b.email) contactParts.push(b.email);
  if (b.phone) contactParts.push(b.phone);
  const loc = [b.location.city, b.location.region, b.location.countryCode]
    .filter(Boolean)
    .join(', ');
  if (loc) contactParts.push(loc);
  if (contactParts.length > 0) lines.push(contactParts.join(' | '));

  const profileParts: string[] = [];
  for (const p of b.profiles) {
    if (p.url) profileParts.push(`[${p.network}](${p.url})`);
    else if (p.username) profileParts.push(`${p.network}: ${p.username}`);
  }
  if (profileParts.length > 0) lines.push(profileParts.join(' | '));

  lines.push('');

  // Summary
  if (b.summary) {
    lines.push('## Summary');
    lines.push(b.summary);
    lines.push('');
  }

  // Experience
  if (doc.work.length > 0) {
    lines.push('## Experience');
    for (const w of doc.work) {
      lines.push(`### ${w.position}, ${w.company}`);
      const range = dateRange(w.startDate, w.endDate, w.current);
      const dateLoc = [range, w.location].filter(Boolean).join(' | ');
      if (dateLoc) lines.push(`*${dateLoc}*`);
      if (w.summary) {
        lines.push('');
        lines.push(w.summary);
      }
      if (w.highlights.length > 0) {
        lines.push('');
        for (const h of w.highlights) lines.push(`- ${h}`);
      }
      lines.push('');
    }
  }

  // Education
  if (doc.education.length > 0) {
    lines.push('## Education');
    for (const e of doc.education) {
      lines.push(`### ${e.studyType} in ${e.area}, ${e.institution}`);
      const range = dateRange(e.startDate, e.endDate, false);
      const extra = [range, e.score ? `GPA: ${e.score}` : ''].filter(Boolean).join(' | ');
      if (extra) lines.push(`*${extra}*`);
      if (e.courses.length > 0) {
        lines.push('');
        lines.push(`Courses: ${e.courses.join(', ')}`);
      }
      lines.push('');
    }
  }

  // Skills
  if (doc.skills.length > 0) {
    lines.push('## Skills');
    for (const s of doc.skills) {
      lines.push(`**${s.category}** (${s.level}): ${s.keywords.join(', ')}`);
    }
    lines.push('');
  }

  // Languages
  if (doc.languages.length > 0) {
    lines.push('## Languages');
    for (const l of doc.languages) {
      lines.push(`- ${l.language} (${l.fluency})`);
    }
    lines.push('');
  }

  // Certifications
  lines.push('## Certifications');
  if (doc.certificates.length > 0) {
    for (const c of doc.certificates) {
      const parts = [c.name];
      if (c.issuer) parts.push(c.issuer);
      if (c.date) {
        const d = formatDate(c.date);
        if (d) parts.push(d);
      }
      lines.push(`- ${parts.join(', ')}`);
    }
  } else {
    lines.push('None listed.');
  }
  lines.push('');

  // Compliance
  const wa = doc.compliance.workAuthorization;
  if (wa.authorized) {
    lines.push('## Work Authorization');
    lines.push(`Authorized to work: ${wa.authorized}`);
    if (wa.countries.length > 0) {
      lines.push(`Countries: ${wa.countries.map((c) => countryLabel(c)).join(', ')}`);
    }
    if (wa.requiresSponsorship) {
      lines.push(`Requires sponsorship: ${wa.requiresSponsorship}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  const genDate = new Date(doc.$credentia.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  lines.push(`*Generated by Credentia One on ${genDate}*`);
  if (doc.$credentia.verifyUrl) {
    lines.push(`*Verification: ${doc.$credentia.verifyUrl}*`);
  }

  return lines.join('\n');
}
