export const SKILL_CATEGORIES: string[] = [
  'Programming Languages',
  'Web Development',
  'Mobile Development',
  'Cloud Computing',
  'Data Science',
  'Machine Learning',
  'Database Management',
  'DevOps',
  'Cybersecurity',
  'Networking',
  'Project Management',
  'Agile Methodologies',
  'Product Management',
  'Business Analysis',
  'Financial Analysis',
  'Accounting',
  'Marketing',
  'Digital Marketing',
  'SEO/SEM',
  'Content Strategy',
  'Sales',
  'Customer Success',
  'Human Resources',
  'Talent Acquisition',
  'Operations Management',
  'Supply Chain',
  'Logistics',
  'Legal',
  'Compliance',
  'Healthcare',
  'Nursing',
  'Engineering',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Architecture',
  'Graphic Design',
  'UX/UI Design',
  'Video Production',
  'Writing',
  'Public Speaking',
  'Teaching',
  'Research',
  'Data Entry',
  'Administrative',
  'Customer Service',
  'Hospitality',
  'Retail',
  'Manufacturing',
  'Quality Assurance',
];
